openapi_webhook:

xiaoetong:
  app_id:
  secret:
  client_id:
  decrypt_key:
  decrypt_token:

# For test, More: https://mp.weixin.qq.com/debug/cgi-bin/sandboxinfo?action=showinfo&t=sandbox/index
wechat:
  app_id:
  secret:

alipay:
  app_id: 2016081500252288
  app_private_key_path: './resources/app_private_test2'
  app_cert_public_key_path: './resources/appCertPublicKey_2016081500252288_test.crt'
  alipay_root_cert_path: './resources/alipayRootCert_test.crt'
  alipay_cert_public_key_path: './resources/alipayCertPublicKey_RSA2_test.crt'

aliyun:
  app_id:
  secret:

tanmarket:
  app_id:
  app_key:

yunduo:
  company_id:
  token:
  general_token:

sms:
  to:
  submail:
    app_id:
    app_key:

doudian:
  app_id:
  secret:
  shop_id:

feishu:
  bot:

wechatpay:
  app_id:
  mch_id:
  api_key_path:

yizhi:
  app_id:
  secret:
  decrypt_key:
  decrypt_token:
